; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = bootloader, app1

; ============= COMMON CONFIGURATION =============
; Base STM32F429 configuration - shared by all apps
[env:stm32f429_base]
platform = ststm32
board = nucleo_f429zi
platform_packages = toolchain-gccarmnoneeabi@^1.140201.0

build_flags =
  -DSTM32F429xx
  -Iframework/CMSIS_CORE/Include
  -Iframework/CMSIS_STM32F4xx/Include
  -Wl,-Map,.pio/build/${PIOENV}/firmware.map
  -fno-unwind-tables
  -fno-asynchronous-unwind-tables

debug_build_flags = -g
monitor_speed = 115200

; ============= BOOTLOADER CONFIGURATION =============
; Base configuration for Bootloader - extends common settings
[env:bootloader]
extends = env:stm32f429_base
build_flags =
  ${env:stm32f429_base.build_flags}
  -DBOOTLOADER
board_build.ldscript = linker/stm32f429zitx/bootloader.ld
build_src_filter =
  +<../src_apps/bootloader/*>
  +<*>
  +<../startup/*>
  +<../framework/CMSIS_STM32F4xx/Source/Templates/system_stm32f4xx.c>
  -<../framework/**>


; ============= APP1 CONFIGURATION =============
; Base configuration for App1 - extends common settings
[env:app1]
extends = env:stm32f429_base
build_flags =
  ${env:stm32f429_base.build_flags}
  -DAPP1
board_build.ldscript = linker/stm32f429zitx/app1.ld
build_src_filter =
  +<../src_apps/app1/*>
  +<*>
  +<../startup/*>
  +<../framework/CMSIS_STM32F4xx/Source/Templates/system_stm32f4xx.c>
  -<../framework/**>